import xyz.wagyourtail.unimined.expect.task.ExpectPlatformJar

plugins {
    id "fabric-loom"
    id 'xyz.wagyourtail.unimined.expect-platform' version '1.0.5'
}
archivesBaseName = "${project.antimatter_archive_base_name}-fabric"

def generatedResources = file("src/generated/resources")
def accessWidenerFile = project(":antimatter-common").file("src/main/resources/antimatter.accesswidener")

repositories {
    maven {
        url = uri("https://storage.googleapis.com/devan-maven/")
    }
    maven { url "https://maven.bai.lol" }
}

loom {
    accessWidenerPath = accessWidenerFile
    mixin {
        defaultRefmapName = "antimatter.refmap.json"
    }
}

sourceSets {
    main {
        resources {
            srcDir generatedResources
        }
    }
}

dependencies{
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.minecraft_version}:${project.mappings_version}@zip")
    }
    implementation(expectPlatform.annotationsDep)
    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    modCompileOnly("dev.latvian.mods:kubejs-fabric:${project.kubejs_version}")
    implementation(project(path: ":tesseract-common")) { transitive false }
    implementation(project(path: ":tesseract-fabric")) { transitive false }
    afterEvaluate {
        include(project(path: ":tesseract-fabric"))
    }
    modImplementation(include("io.github.fabricators_of_create:Porting-Lib:${project.port_lib_version}-beta+1.18.2-stable")){
        exclude(group: "net.fabricmc.fabric-api")
        exclude(group: "com.github.LlamaLad7")
    }
    modImplementation(include("io.github.tropheusj:serialization-hooks:0.3.23")){
        exclude(group: "net.fabricmc.fabric-api")
        exclude(group: "com.github.LlamaLad7")
    }
    modImplementation(include("net.feltmc:felt-recipe-api:1.0.1")){
        exclude(group: "net.fabricmc.fabric-api")
        exclude(group: "com.terraformersmc")
    }
    modImplementation(include("net.feltmc:felt-player-item-api:1.1.0")){
        exclude(group: "net.fabricmc.fabric-api")
        exclude(group: "com.terraformersmc")
    }
    modImplementation(include("net.feltmc:felt-enchanting-api:1.1.0")) { transitive false }
    modImplementation(include("org.gt-reimagined:structurelib-fabric:${project.structurelib_version}-${project.minecraft_version}"))
    modImplementation(include("dev.trinsdar:arrp:0.6.7"))
    modCompileOnly("com.blamejared.crafttweaker:CraftTweaker-fabric-1.18.2:${project.crafttweaker_version}")
    modCompileOnly(include("dev.trinsdar:ct-fabric-fluid-support:1.0.2"))
    modImplementation "me.shedaniel:RoughlyEnoughItems-fabric:${project.rei_version}"
    modCompileOnly("mezz.jei:jei-${project.minecraft_version}-fabric:${project.jei_version}"){
        exclude(group: "mezz.jei", module: "jei-1.18.2-fabric-api")
    }
    modImplementation("teamreborn:energy:${project.energy_version}") {
        transitive = false
    }
    implementation(annotationProcessor(include("io.github.llamalad7:mixinextras-fabric:0.2.0-beta.11")))
    modImplementation("earth.terrarium:botarium-fabric-1.18.2:${project.botarium_version}"){
        transitive = false
    }
    modImplementation("com.teamresourceful.resourcefullib:resourcefullib-fabric-1.18.2:${project.resourcefullib_version}")
    modRuntimeOnly("com.terraformersmc:modmenu:${project.mod_menu_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }
    implementation("com.electronwill.night-config:toml:${project.nightconfig_version}")
    implementation("com.electronwill.night-config:core:${project.nightconfig_version}")
    modImplementation "maven.modrinth:carbon-config:${project.carbon_config_fabric_version}"
    modCompileOnly("curse.maven:the-one-probe-fabric-581847:${project.top_fabric_file}")
    modCompileOnly "lol.bai.megane:megane-reborn-energy:${project.megane_version}"
    modCompileOnly "lol.bai.megane:megane-api:${project.megane_version}"
    modCompileOnly("com.simibubi.create:create-fabric-${minecraft_version}:0.5.0.i-944+1.18.2"){
        transitive = false
    }
    //include("org.jetbrains.kotlin:kotlin-reflect:${kotlin.coreLibrariesVersion}")
    //include("org.jetbrains.kotlin:kotlin-stdlib:${kotlin.coreLibrariesVersion}")
    //include("org.jetbrains.kotlin:kotlin-stdlib-common:${kotlin.coreLibrariesVersion}")
}

// The AW file is needed in :fabric project resources when the game is run.
task copyAccessWidener(type: Copy) {
    from accessWidenerFile
    into generatedResources
}


processResources {
    dependsOn copyAccessWidener
    from(project(":antimatter-common").sourceSets.main.resources){
        exclude("antimatter.accesswidener")
    }
    def toReplace = [
            "version"             : project.mod_version
    ]

    inputs.properties toReplace
    filesMatching("fabric.mod.json") {
        expand toReplace
    }
}
tasks.named('compileJava', JavaCompile) {
    source(project(":antimatter-common").sourceSets.main.allSource)
}

sourcesJar {
    mustRunAfter copyAccessWidener
    from(project(':antimatter-common').sourceSets.main.allSource){
        exclude("antimatter.accesswidener")
    }
}

tasks.create("platformJar", ExpectPlatformJar){
    platformName = "fabric"
    inputFiles = sourceSets.main.output
    archiveClassifier.set "dev"
    remap = [
            "xyz/wagyourtail/unimined/expect/annotation/Environment": "net/fabricmc/api/Environment",
            "xyz/wagyourtail/unimined/expect/annotation/Environment\$EnvType": "net/fabricmc/api/EnvType",
    ]
}

remapJar {
    inputFile.set platformJar.archiveFile
    dependsOn platformJar
    archiveClassifier.set null
}

jar{
    archiveClassifier.set "dev-unmapped"
}

publishing {
    publications {
        mavenJava(org.gradle.api.publish.maven.MavenPublication) {
            artifactId = project.name
            from components.java
        }
    }

    repositories {
        def isCI = System.getenv("CI")
        def isRELEASE = System.getenv("GITHUB_RELEASE")
        if (isRELEASE){
            maven {
                name = "GTMaven"
                url = "https://repo.repsy.io/mvn/trinsdar/gregtech-intergalactical/"
                credentials {
                    username = System.getenv("MAVEN_USERNAME")
                    password = System.getenv("MAVEN_PASSWORD")
                }
            }
        } else if (isCI) {
            maven {
                url System.getenv("local_maven_url")
            }
        } else {
            mavenLocal()
        }
    }
}