# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true

#mod properties
mod_version=0.3.1-alpha.8
archive_base_name=GT-Lib
mod_id=gtlib
maven_group=org.gt-reimagined

mdg_version=2.0.82
mappings_version=2022.03.13
minecraft_version=1.18.2
forge_version=40.2.4

#dependencies
tesseract_version=1.0.0-alpha.5
jei_version=10.2.1.1004
crafttweaker_version=9.1.90
kubejs_version=1802.5.1-build.329
rhino_version=1802.2.1-build.255
architectury_version=4.12.94
nightconfig_version=3.6.5
rei_version=8.3.557
cloth_config_version=6.5.133
arrp_version=0.6.7.1
terraform_version=3.1.5
resourcefullib_version=0.0.5
structurelib_version=2.0.0
carbon_config_fabric_version=9SdinCkI
carbon_config_forge_version=u2cqt0OR
kotlin_version=1.8.21
ponder_version=0.5.8
catnip_version=0.5.9

architectury_file=3728618
top_forge_file=3671753
curios_file=4985315
jade_version=5079263

tesseract_archive_base_name=TesseractAPI