modLoader="javafml"
license="LGPLv3"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/GT-Reimagined/GT-Lib/issues"

[[mods]]
modId="gtlib"
version="${version}"
displayName="GTLib"
displayURL="https://github.com/GT-Reimagined/GT-Lib"
credits="mitchej123, e99999, qubka, Vliro, repolainen, Muramasa, Rongmario for original AntimatterAPI"
authors="Trinsdar"
description='''Well-rounded API for Minecraft, primarily made for GregTech.'''
[[dependencies.gtlib]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="AFTER"
side="BOTH"
[[dependencies.gtlib]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="AFTER"
side="BOTH"
[[dependencies.gtlib]]
modId="kotlinforforge"
mandatory=true
versionRange="${kff_version_range}"
ordering="AFTER"
side="BOTH"
[[dependencies.gtlib]]
modId="carbonconfig"
mandatory=true
versionRange="[1.20-1.2.0,)"
ordering="AFTER"
side="BOTH"
[[mods]]
modId="gt"
version="${version}"
displayName="GT Shared Data"
displayURL="https://github.com/GT-Reimagined/GT-Lib"
#logoFile="examplemod.png"
credits="mitchej123, e99999, qubka, Vliro, repolainen, Muramasa, Rongmario for original AntimatterAPI"
authors="Trinsdar"
description='''Modid used for data shared betwen gtlib addons'''
[[dependencies.gt]]
    modId="gtlib"
    mandatory=true
    versionRange="[0.0.1,)"
    ordering="AFTER"
    side="BOTH"