plugins {
    id 'xyz.wagyourtail.unimined' version "1.3.10-SNAPSHOT"
    id 'xyz.wagyourtail.unimined.expect-platform' version '1.0.5'
}

archivesBaseName = "${rootProject.antimatter_archive_base_name}-forge"

configurations {
    modCompileOnly
    compileOnly.extendsFrom modCompileOnly
    modRuntimeOnly
    runtimeOnly.extendsFrom modRuntimeOnly
}

unimined.minecraft {
    version(project.minecraft_version)
    minecraftForge {
        loader(project.forge_version)
        mixinConfig = [
                "antimatter.mixins.json",
                "antimatter-forge.mixins.json",
                "antimatter.rei.mixins.json"
        ]
    }
    defaultRemapJar = true

    mappings {
        searge()
        mojmap()
        devFallbackNamespace "official"
        devNamespace "mojmap"
        parchment(rootProject.minecraft_version, rootProject.mappings_version)
    }

    mods {
        remap(configurations.modCompileOnly){
            catchAWNamespaceAssertion()
            namespace("searge")
        }
        remap(configurations.modRuntimeOnly){
            catchAWNamespaceAssertion()
            namespace("searge")
        }
        modImplementation {
            catchAWNamespaceAssertion()
            namespace("searge")
        }
    }
}

jarJar.enable()

dependencies {
    implementation(expectPlatform.annotationsDep)
    implementation(project(path: ":tesseract-forge"))
    implementation(project(path: ":tesseract-common"))
    afterEvaluate {
        include(project(path: ":tesseract-forge"))
    }

    //MIXIN
    annotationProcessor 'org.spongepowered:mixin:0.8.5-SNAPSHOT:processor'
    //modCompileOnly("mezz.jei:jei-${rootProject.minecraft_version}-forge:${rootProject.jei_version}")
    //modRuntimeOnly("mezz.jei:jei-${rootProject.minecraft_version}-forge:${rootProject.jei_version}")
    modImplementation("mezz.jei:jei-1.18.2:9.7.2.1001")
    modCompileOnly("me.shedaniel:RoughlyEnoughItems-forge:${rootProject.rei_version}")
    modCompileOnly("me.shedaniel.cloth:cloth-config-forge:6.5.133")
    modImplementation("com.blamejared.crafttweaker:CraftTweaker-forge-1.18.2:${rootProject.crafttweaker_version}")
    modImplementation(include("dev.trinsdar:arrp-forge:0.6.7"))
    modImplementation(include("dev.trinsdar:terraform-utils-v1:3.1.5"))
    modImplementation(include("earth.terrarium:botarium-forge-1.18.2:${project.botarium_version}"))
    modImplementation(include("org.gt-reimagined:structurelib-forge:${project.structurelib_version}-${project.minecraft_version}"))
    modImplementation(include("com.teamresourceful.resourcefullib:resourcefullib-forge-1.18.2:${project.resourcefullib_version}"))
    modImplementation("maven.modrinth:carbon-config:${project.carbon_config_forge_version}")
    jarJar("maven.modrinth:carbon-config:${project.carbon_config_forge_version}"){
        jarJar.ranged(it, "[1.18.2-1.2.6,)")
    }
    modImplementation("dev.latvian.mods:kubejs-forge:${rootProject.kubejs_version}")
    modImplementation("dev.latvian.mods:rhino-forge:${rootProject.rhino_version}")
    modImplementation("dev.architectury:architectury-forge:${rootProject.architectury_version}")
    modImplementation("curse.maven:the-one-probe-245211:${rootProject.top_forge_file}")
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation(include("io.github.llamalad7:mixinextras-forge:0.4.1"))
    modCompileOnly("com.simibubi.create:create-${minecraft_version}:0.5.1.i-435:all"){
        transitive = false
    }
    //include("org.jetbrains.kotlin:kotlin-reflect:${kotlin.coreLibrariesVersion}")
    //include("org.jetbrains.kotlin:kotlin-stdlib:${kotlin.coreLibrariesVersion}")
    //include("org.jetbrains.kotlin:kotlin-stdlib-common:${kotlin.coreLibrariesVersion}")
}

tasks.withType(JavaCompile).configureEach {
    source(project(":antimatter-common").sourceSets.main.allSource)
    /*expectPlatform.insertAgent(it, "forge", ["xyz/wagyourtail/unimined/expect/annotation/Environment": "net/minecraftforge/api/distmarker/OnlyIn",
                                             "xyz/wagyourtail/unimined/expect/annotation/Environment\$EnvType": "net/minecraftforge/api/distmarker/Dist",
                                             "xyz/wagyourtail/unimined/expect/annotation/Environment\$EnvType.SERVER": "DEDICATED_SERVER",])*/
}

processResources {
    from project(":antimatter-common").sourceSets.main.resources
    inputs.property "version", project.mod_version

    exclude("antimatter.accesswidener")
    filesMatching("META-INF/mods.toml") {
        expand "version": project.mod_version
    }
}

sourcesJar {
    from(project(':antimatter-common').sourceSets.main.allSource)
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : "Trinsdar",
                'Specification-Version'   : '1', // We are version 1 of ourselves
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : "Trinsdar",
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

publishing {
    publications {
        mavenJava(org.gradle.api.publish.maven.MavenPublication) {
            artifactId = project.name
            from components.java
            jarJar.component(it)
        }
    }
    repositories {
        def isCI = System.getenv("GITHUB_ACTION")
        def isRELEASE = System.getenv("GITHUB_RELEASE")
        if (isCI && isRELEASE) {
            maven {
                url = "https://repo.repsy.io/mvn/trinsdar/gregtech-intergalactical/"
                credentials {
                    username = System.getenv("MAVEN_USERNAME")
                    password = System.getenv("MAVEN_PASSWORD")
                }
            }
        } else {
            mavenLocal()
        }
    }
}
