plugins {
    id "net.neoforged.moddev.legacyforge"
    id 'xyz.wagyourtail.unimined.expect-platform' version '1.0.5'
}

archivesBaseName = "${project.antimatter_archive_base_name}-forge"

neoForge {
    version = "${project.minecraft_version}-${project.forge_version}"
    def at = project(':antimatter-common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    parchment {
        minecraftVersion = project.minecraft_version
        mappingsVersion = project.mappings_version
    }
    runs {
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

mixin {
    add sourceSets.main, "antimatter.refmap.json"
    config "antimatter.mixins.json"
    config "antimatter-forge.mixins.json"
    config "antimatter.rei.mixins.json"
}


dependencies {
    implementation(expectPlatform.annotationsDep)
    implementation(project(path: ":tesseract-forge"))
    implementation(project(path: ":tesseract-common"))
    compileOnly(project(":antimatter-common"))
    jarJar("org.gt-reimagined:tesseract-forge:0.2.4-1.18.2"){
        version {
            strictly("[0.2.4-1.18.2,)")
            prefer("[0.2.4-1.18.2,)")
        }
    }

    //MIXIN
    annotationProcessor 'org.spongepowered:mixin:0.8.5-SNAPSHOT:processor'
    implementation("org.jetbrains:annotations:26.0.1")
    compileOnly("org.lwjgl:lwjgl-opengl:3.2.2")
    //modCompileOnly("mezz.jei:jei-${rootProject.minecraft_version}-forge:${rootProject.jei_version}")
    //modRuntimeOnly("mezz.jei:jei-${rootProject.minecraft_version}-forge:${rootProject.jei_version}")
    modImplementation("mezz.jei:jei-1.18.2:9.7.2.1001")
    modCompileOnly("me.shedaniel:RoughlyEnoughItems-forge:${project.rei_version}")
    modCompileOnly("me.shedaniel.cloth:cloth-config-forge:6.5.133")
    modImplementation("com.blamejared.crafttweaker:CraftTweaker-forge-1.18.2:${project.crafttweaker_version}")
    modImplementation(include("dev.trinsdar:arrp-forge:0.6.7"))
    modImplementation(include("dev.trinsdar:terraform-utils-v1:3.1.5"))
    modImplementation(include("earth.terrarium:botarium-forge-1.18.2:${project.botarium_version}"))
    modImplementation(include("org.gt-reimagined:structurelib-forge:${project.structurelib_version}-${project.minecraft_version}"))
    modImplementation(include("com.teamresourceful.resourcefullib:resourcefullib-forge-1.18.2:${project.resourcefullib_version}"))
    modImplementation("maven.modrinth:carbon-config:${project.carbon_config_forge_version}")
    jarJar("maven.modrinth:carbon-config:${project.carbon_config_forge_version}"){
        version {
            strictly("[1.18.2-1.2.6,)")
            prefer("[1.18.2-1.2.6,)")
        }
    }
    modImplementation("dev.latvian.mods:kubejs-forge:${project.kubejs_version}")
    modImplementation("dev.latvian.mods:rhino-forge:${project.rhino_version}")
    modImplementation("dev.architectury:architectury-forge:${project.architectury_version}")
    modImplementation("curse.maven:the-one-probe-245211:${project.top_forge_file}")
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation(include("io.github.llamalad7:mixinextras-forge:0.4.1"))
    modCompileOnly("com.simibubi.create:create-${minecraft_version}:0.5.1.i-435:all")
    //include("org.jetbrains.kotlin:kotlin-reflect:${kotlin.coreLibrariesVersion}")
    //include("org.jetbrains.kotlin:kotlin-stdlib:${kotlin.coreLibrariesVersion}")
    //include("org.jetbrains.kotlin:kotlin-stdlib-common:${kotlin.coreLibrariesVersion}")
}

Dependency include(Object dep){
    dependencies.jarJar(dep){
        version {
            strictly("[${it.version},)")
            prefer(it.version)
        }
    }
}

tasks.named('compileJava', JavaCompile) {
    source(project(":antimatter-common").sourceSets.main.allSource)
    /*expectPlatform.insertAgent(it, "forge", ["xyz/wagyourtail/unimined/expect/annotation/Environment": "net/minecraftforge/api/distmarker/OnlyIn",
                                             "xyz/wagyourtail/unimined/expect/annotation/Environment\$EnvType": "net/minecraftforge/api/distmarker/Dist",
                                             "xyz/wagyourtail/unimined/expect/annotation/Environment\$EnvType.SERVER": "DEDICATED_SERVER",])*/
}

processResources {
    from project(":antimatter-common").sourceSets.main.resources
    inputs.property "version", project.mod_version

    exclude("antimatter.accesswidener")
    filesMatching("META-INF/mods.toml") {
        expand "version": project.mod_version
    }
}

sourcesJar {
    from(project(':antimatter-common').sourceSets.main.allSource)
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : "Trinsdar",
                'Specification-Version'   : '1', // We are version 1 of ourselves
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : "Trinsdar",
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

publishing {
    publications {
        mavenJava(org.gradle.api.publish.maven.MavenPublication) {
            artifactId = project.name
            from components.java
        }
    }
    repositories {
        def isCI = System.getenv("CI")
        if (isCI) {
            maven {
                url System.getenv("local_maven_url")
            }
        } else {
            mavenLocal()
        }
    }
}
