name: Test Changelog
on:
  workflow_dispatch:
jobs:
  release:
    strategy:
      matrix:
        # Use these Java versions
        java: [17]
        # and run on both Linux and Windows
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout GT-Lib
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Fetch tags
        run: git fetch --tags
      - name: Make build dir
        run: mkdir build
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ignorePreReleases: true
          outputFile: build/changelog.md
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>\n#{{RELEASE_DIFF}}"
            }
      - name: Output changelog
        run: cat build/changelog.md